package com.desafio.desafio.exception;

public class RecordNotFoundException extends RuntimeException {
    
    public RecordNotFoundException(String msg) {
        super(msg);
    }
}
